### ISSUE TITLE
Nightly builds not supported

### ISSUE THREAD

**Issue by mearns** [semver/semver#200] opened 2014-05-20 16:05 UTC
I really like semver except for specification that all strings following the Major.minor.patch version number indicate a pre-release. I feel that this is inconvenient for, if not incompatible with, rapid development environments with development builds (e.g., nightly snapshot builds).

In my team, we do not always know what the version number of the next release will be, because we don't know what kind of changes will be ready for inclusion when it is time to release. We therefore do not bump the version number until the release. Instead, we add a "post-release" suffix to the version string immediately after the release. For instance, we release version 1.0.0, and then add the string "-dev" to the version string, so that until the next release, we are all working with version 1.0.0-dev. Nightly builds will include this suffix on the version string, indicating that it is a development build.

Conceptually, it is very similar to the idea of a pre-release identifier as you've described it, but the important difference is that its precedence is _higher_ than the version number it attaches to. Again, this is because we don't know if the next release is going to 1.0.1 with a critical bug fix the next day, or 1.1.0 with new features sometime next month.

I would love to see semver updated to support such a feature, though I'm not sure how exactly it could be incorporated without breaking backward compatibility. Perhaps this could be worked into semver ver 3.0, unless you have a suggestion for how semver can handle nightly builds.

**Comment by JamesMGreene** [comment] 2015-06-09 17:34
By the way, please take a look at this semi-related issue that I opened, discussed, and ended up closing: #242

The discussion may be more specific to my particular use case (wrapping an external dependency) but there's definitely a substantial amount of merit/insight to be gained within, IMHO.  You can ignore the opening discussion and skip ahead to where we discuss build metadata (in the fashion akin to @jeffhandley's notes here for NuGet).

Additionally, I would agree that we really still need post-release versioning added to SemVer while _also_ maintaining the build metadata concept (but ideally with an indicator other than the misappropriated `+` :wink:).

**Comment by Abdillah** [comment] 2015-07-28 03:22
I have some view on this (nightly build).

When RAD or Nightly Build is applied, I assume that pre-release is vacum; means the development do not need to use alpha, beta, etc. Is it right @mearns?

Then, why don't SemVer gives more freedom on this pre-release "tuple"? I mean instead of specify after a dash is pre-release, SemVer can generalize that it is a tuple representing development stage. It can either pre-release or post-release. But, a project MUST consistent on using it and MUST included explanation on documentation. Moreover, whether pre- or post-release considered as unstable, and both is necessary for API user to review before using or Use at Your Own Risk :tm:.

I do agree with separating post- and pre-. But, if the addition of feature means minor change in SemVer, then above is an addition IMO, and can be merged soon. 

Maybe we can have queue on what major issue (leading to major change) need to be addressed and wait if we are ready for `v3.0.0`. Then, when `v3.0.0` is the next step, just merge them all!

#### Trivia
I feel SemVer community itself is fear of bumping major version (fear of having `v3.0.0`). Then, how do the adopters?

Don't take this seriously, except you are agree :smile:..

**Comment by olivier-spinelli** [comment] 2015-08-31 17:04
The contributors of this issue may be interested in http://csemver.org (where C stands for Constrained).
Based on CSemVer, CSemver-CI *LastReleasedBased* semantic versions de facto support a "Post Release" versionning scheme. I'm having fun designing it, it is totally open to discussion (beta version) and would love to share this beast with anyone interested in this subject.

**Comment by mearns** [comment] 2015-08-31 18:31
@Abdillah 

No, the use of post releases doesn't necessarily mean that pre-releases aren't used. My point is that many agile teams don't know until near the end of the development cycle which changes are going to be included in the next release, so they don't know what the next version number will be.

I don't think just documenting in your code whether you use the field for pre-release or post-release is sufficient. The idea of semvar is that you can understand version numbers the same way across different projects, and write tools that correctly parse them across projects. So if my "post release" field means that it comes after the version, but you use the same field as a "pre release" to indicate that it comes before the version, then the tools won't know what to do.

I've lost track of the conversation, so I don't remember why this was rejected, by my idea was to simply use a different character to indicate whether a suffix is a pre-release or a post release.

Regarding fear of bumping major version: there should be fear. Bumping the major version means you've broken compatibility. Any software that depends on your project is now broken. You should do this as rarely as possible. Ideally, everything would always be major version 1.

**Comment by FichteFoll** [comment] 2015-08-31 20:34
>I've lost track of the conversation, so I don't remember why this was rejected, by my idea was to simply use a different character to indicate whether a suffix is a pre-release or a post release.

I never understood it anyway [the reason for rejection]. It also makes more sense semantically to *not* use `+` for "build metadata" but for post-release versioning and instead use something like `~` for the metadata, which I'm still a huge supporter of.

It should be clear that this change requires a major bump of the semver spec itself.

**Comment by judgeaxl** [comment] 2015-10-26 03:51
Just some thoughts, as I've been following this for some time, and versioning in general for many years.

As has been mentioned above, a pre-release version can not be counted on to formally follow the rules, in terms of compatibility.

I tend to immediately after a release increment the minor version and attach a pre-release tag, because the next feature release will have to be a minor bump at minimum. In my case, patches are developed on the release branch and automatically get a patch bump, not on the development branch. When it comes time to release, I can make the final decision to keep that minor bump, or go full major, depending on what the changes ended up being.

If a project does publish nightly pre-release builds, then whoever wants to use them need to realize that such a release may be unstable, might not work at all, or change everything. If a team depends on nightly releases of lots of components and this causes problems, then perhaps they need to re-think their approach. If you don't want to expose that kind of uncertainty, then you kind of have to bump the versions and make actual releases instead.

As for internal users, I think they'll just have to look at the changes, or talk to the team, if they absolutely have to work off of the bleeding edge, because any amount of version numbers are not going to solve all possible problems, IMHO.

**Comment by ygoe** [comment] 2017-11-26 14:26
I stopped reading the comments at some point when it started going in circles, sorry for that.

From the first few comments I see two possible solutions:

* Reinterpret the `+` as "post-release" instead of metadata. Who needs metadata? This is a version identifier. Descriptive metadata can go in the release notes or marketing materials. This would mean a change to the SemVer spec and considering the `+` suffix would become mandatory instead of optional. Post-releases then fall into the same class as pre-releases as to suggesting them to a user.
* Increment the patch number by 1 and use `-` pre-releases towards that. This is possible today.

I see the problem with the second solution: You still assume version compatibility and temporary incompatible changes would result in unnecessary version increments.

I'd suggest the following change of mind for this: No pre-release is ever "compatible" with anything but itself. Pre-releases are marked as such for a reason. They may contain any kind of changes at any time. Use them only if you know exactly what you get. So I don't care if 1.0.0 or 1.0.1 are in any way compatible with 1.0.1-something. All I care is that 1.0.0 is compatible with 1.0.1.

Is this interpretation acceptable for SemVer?

**Comment by mearns** [comment] 2017-11-27 01:08
In the interest of preserving backwards compatibility for semver, I would support your suggestion (the second bullet) of reinterpreting pre-release to not specify any particular compatibility. I don't think it's the ideal spec, but it is preferable to making incompatible changes to semver.

**Comment by jwdonahue** [comment] 2017-12-06 03:24
I think #'s 10 and 11 need to be modified. Rather than calling it build metadata, just call it user-defined data. Whether/how user defined data is applied to precedence is user defined and not covered in the spec.  Then users can define their own sort-able, non-sort-able fields and invent whatever semantics they need to have, on top of SemVer.

I also think we need a version meta tag that is defined in a separate standard from SemVer, that can be used to reference specific version schema's that define all of the semantics for a particular version string, whether it's SemVer, Nuget, RPM, etc.  It would likely be something that is separated by white space from the version string, and probably should be required to be on the same line. Then SemVer could provide a baseline schema defining its versioning semantics and tool chain makers could add to that to describe the semantics of their user data.

Hope that makes enough sense to get the point across, because I am not ready to present any fleshed out written proposals just yet.

**Comment by olivier-spinelli** [comment] 2017-12-06 10:00
As it has been stated previously in this thread, SemVer is a foundation onto which more elaborated processes, workflows and tools can be built. After a lot of hesitations I choose to embrace it AND build something on it. Two of my main concern were:
- Nice, automatic and readable handling of "post release" (for the CI builds).
- Limiting human mistakes by enforcing valid version transitions ("Can a 1.0.1-beta follow a 0.9.0?")

Since I started this work a long ago, one key aspect was that Nuget was not semver compliant: my versions must work with the poor handling of Nuget regarding prerelase part...
I also wanted a correct low-level tagging of my artifacts by using the windows FileVersion in a coherent manner and be able to fix prereleases.

I ended with CSemVer that works great for us. It may interest some of you: http://csemver.org/ (do not hesitate to test the playground :)).

An implementation is available here: https://github.com/SimpleGitVersion/CSemVer-Net that contains a parsers for SVersion (SemVer) and CSVersion (for CSemVer versions) with all the Predecessors/Successors computations.

**Comment by ygoe** [comment] 2017-12-08 20:02
That CSemVer looks overly complicated to me. I don't think I'll ever see the need for that.

**Comment by mentalisttraceur** [comment] 2018-08-17 22:09
Been fighting with this a bit in my own work lately, and thinking about this a lot. I suggest the following approach, which just **discards** the idea of trying to bend SemVer to fit CI builds:

1. When possible, SemVer is just **not used** for development/nightly builds where the actual future release number is not yet determinable for sure.

2. When not possible, *drop version to a 0.0.0 **pre-release***. SemVer's clause about there not being backward compatibility guarantees in major version 0 serves as an escape hatch, and the intentionally lower-than-any-real-release sorting has the advantage that a user has to know what they're doing and explicitly require your not-really-an-actual-official-release version.

Some people above apparently want their development builds to explicitly sort above their extant releases, and I can understand why that can be useful in some cases, like purely internal testing depending on automatic "get latest" behavior, where it doesn't matter how much you break SemVer.

It is in the releases to the external world that SemVer matters, and there, users almost never want to be able to *accidentally* upgrade to your *development* builds, and if they do, then by all rights it *ought to be* an official release.

(Incidentally, it looks like @olivier-spinelli had the same idea as my point 2 above, with the CSemVer-CI zero-based concept.)

Key point: SemVer signals "pay attention" information to those who depend on your software - with normal releases you can break that "pay attention" signaling into semantically meaningful numbers. We can't meaningfully segment the sort of *arbitrary and unpredictable* changes that arise in development work that hasn't yet made the cut into a release yet.

**Comment by mentalisttraceur** [comment] 2018-08-17 22:27
I have concerns about the pre-releases don't guarantee backwards compatibility model: Say I have a package that depends on the major version 1 of your package.

You upload a `1.2.3`, which is backwards compatible, then a `1.2.4-dev3232` which isn't. This raises questions:

1. Is it common/ubiquitous for SemVer package managers to reject pre-leases and only install finished releases?

2. If I released my package two years ago and happily moved on to other things, *not* having precluded pre-releases from my dependency specification, then the developer of a package I depend on starts publishing pre-releases using newly accepted "pre-releases don't guarantee backwards compatibility" semantics, they might upload a version that breaks my package, which in turn breaks my users.

3. From a human-compatibility perspective (teaching/learning SemVer) would this change complect things too much? Instead of just explaining the "major - backwards incompatible, minor - new feature, patch - bugfix" top-level view, it becomes *very important* to emphasize "except when there's a `-` after, then it's a pre-release".

**Comment by jwdonahue** [comment] 2018-08-18 02:59
@mearns, -dev is poor choice for CI builds.  -alpha < -beta < -dev, probably not what you want, so you have to do something like -a.dev < -alpha < -beta.

It seems that some of the folks on this thread have come to the erroneous conclusion that a "release" is a package with a non-prerelease version string (ie; 1.0.0, 1.0.0+buildmeta) and that the prerelease tag is only useful _before_ a "release".  This not what is meant by the English word "release" or the spec. A release is anything that is publicly available, no matter what tags it has on it. By "publicly available" I mean; available in its fully packaged form across a network connection (including sneaker-nets!). I wish the spec used the term "published" instead.

Every published package must have a unique version string attached.  As some have pointed out, a prerelease tag loosens the compatibility constraints on the version triple. This enables CI builds to simply bump the patch number on each build and apply a prerelease tag indicating the product may be unstable.  I always use something along the lines of -a.dev+branch for CI builds. Then "release builds", or rather official stable releases can be selected from a set of recent CI builds and repackaged with the appropriate non-prerelease version triple, based on the content of that release.

You get histories with parallel release trains like this:

```
0.1.0-a.dev+feat1  // First feature.
  // PubInt pulls from feat1
  1.0.0-a.flight1+PubInt // Internal adopters.
  1.0.0-a.flight2+PubInt// Wider audience.
    // PubExt pulls from PubInt
    1.0.0-alpha+PubExt // External early adopters.
0.1.1-a.dev+feat1 // Bug fix.
  // PubInt pulls fix from feat1
  1.0.1-a.flight1+PubInt 
    // Oops! hot fix needed everywhere, no time/need for flight2.
    // PubExt pulls from PubInt
    1.0.1-alpha+PubExt
1.1.0-a.dev+feat2 // Work begins on the next feature.
    // Feedback from alpha customers is good.
    1.0.1-beta+PubExt // Wider audience.
    // Feed back from beta customers is good.
    1.0.1+PubExt // First stable release.
// Mean while, work continues in feat2
1.1.0-a.dev+feat2 // WIP
1.1.1-a.dev+feat2 // WIP
  // PubInt pulls from feat2
  1.1.1-a.flight1+PubInt
1.1.3--a.dev+feat2 // WIP
  // PubInt pulls from feat2
  1.1.3-a.flight1+PubInt
    // PubExt pulls from PubInt
    1.1.3-alpha+PubExt
    1.1.3-beta+PubExt
    1.1.3+PubExt // Second stable release.
...
```

One useful technique is for CI builds to release packages that include the branch in the package name:

```
XRay.Feat1 0.1.0-a.dev+buildmeta // Available to dev/test only.
XRay.PubInt 0.1.0-a.flight1+buildmeta // Available to internal dog-food eaters.
XRay 1.0.0 // PubExt uses just the product name in packaging.

```
This can be very helpful when you have multiple parallel feature branches:

```
XRay.origin 0.0.y-a.dev // Primed with minimal common content.
XRay.feat1 0.1.0-a.dev+origin // feat1 derives from origin.
XRay.feat2 0.1.0-a.dev+origin // feat2 derives from origin.
XRay.feat3 0.1.0-a.dev+feat1  // feat3 derives from feat1.
XRay.feat4 0.1.0-a.dev+feat2  // feat4 derives from feat2.
// Origin merges feat1
XRay.origin 0.1.0-a.dev
// Origin merges Feat4
XRay.origin 0.2.0-a.dev
...

```
In this scenario, PubInt and PubExt would pull from origin. None of the feature branches need have any knowledge of the published package version history, they simply maintain their own version history and their packages never collide with versions from other branches.

The semver scheme could not work with just a postrelease tag, so you'd have to have both if had postrelease, but you can easily get by with just the prerelease tag and that's why semver has one. 

@mearns, it's unlikely that any new tags or fields will be accepted into the semver spec. There have been other post-release proposals that have died on the vine.  Unless you intend to issue a PR for whatever changes you have in mind or you have additional questions, please close this thread at your earliest possible convenience.

**Comment by olivier-spinelli** [comment] 2018-08-19 07:30
It seems to me that the issue is about "post-release" builds. SemVer handles "pre-release" but not "post-release". I wanted post-release support and a safe resolution of versions. My answer has been:

- First: to define a subset of SemVer with standardized versions (called CSemVer versions). No more "2.0.0-final" that is BEFORE "2.0.0-update"!
- Second: based on this perfectly defined possible versions, "inject" -CI versions into them in a way that the SemVer ordering rules guaranty an absolute ordering of all the kind of versions

CI versions are necessarily after their base (the last CSemVer version) and before any possible future CSemVer version.
There is no graph/tree (except if you use different suffixes for different branches of CI versions). Only a totally ordered (unambiguous) set of versions that will safely be handled by any package manager.

There are more things in CSemVer but, at least, it gives me the "post-release" semantic I needed.

For whom it may interest, it's here: http://csemver.org (git page).

**Comment by jwdonahue** [comment] 2018-08-19 15:16
@olivier-spinelli, it's another way to do things. The real problem is how to communicate the syntax, semantics and related processes that cause a specific release in a way that machines and humans can reason over.  See [https://versionmeta.org](https://versionmeta.org). It's still a work in progress. Good weather has kept me away from my machine the past few months.

**Comment by judgeaxl** [comment] 2018-08-20 02:02
@olivier-spinelli, just out of curiosity, what, in your opinion, is the difference between a "post-release" build and a "pre-release" build, assuming all branches may eventually converge into a release? I.e. is a build after 1.0.0 a post-release build of 1.0.0 or a pre-release build of 1.0.1 (or 1.1.0)? When would it change from one to the other?

I've been experimenting with using the `-alpha` pre-release for dev builds, with meta data for branches and features attached. Develop builds are always a minor version higher than the last release branch, unless I explicitly say it's a major increment. Release builds are always `-beta` until they get released. Hot fix branches off of each release (or commits on the release branch post the actual release tag) always have a patch version increment and a `-beta` pre-release. This has worked well enough not to warrant any amendments to SemVer so far.

I also consider any `-alpha` build to essentially have the same semantics as a `0.0.0` build, i.e. anything can be broken or incompatible for an arbitrary length of time. SemVer restrictions are not enforced until before the next release branch is created, or someone complains loudly enough.

I'm primarily developing libraries, frameworks, and packaged apps, so I've not tried this with any sort of continuous service deployment.

**Comment by olivier-spinelli** [comment] 2018-08-21 06:37
@jwdonahue, you're right, it's all about semantics **to the developers** (meaning actual devs but also sysops, maintainers, etc.). This is why I wanted the published versions to be fundamentally unambiguous, based on total order.

**Comment by olivier-spinelli** [comment] 2018-08-21 06:52
@judgeaxl, I tried using a more relaxed scheme as yours with (hopefully orthogonal) features in different packages. I stopped and converged to this very simple linear model.

To directly answer your question: a post-release build is a CI-build. There is no human involved in the process since there is no "actual version" to set. The only thing we know is that the component/artifact is the 4th after the 2.0.1-rc... However, technically, it is a fully valid artifact that can be consumed by any other Solutions that uses it.
Actual releases, the one where a human (potentially helped by tools that try to detect breaking changes/evolutions/fix) has to choose a version are manually triggered at any time and they can be "Pre-Release" (alpha, beta, etc.) as well as "Official Release".

(Side note about automated tools: I don't believe in any tool that will decide on its own whether the major/minor/patch has to be incremented, they only can prevent/signal some obvious changes and prevent human mistakes.)

**Comment by jwdonahue** [comment] 2018-08-21 15:12
@olivier-spinelli, take a look at https://versionmeta.org and http://versionschema.org (finally published the first version). I suspect we could define your csemver using version schema. VersionSchema has some potential advantages over SemVer and other schemes because it should be able to unambiguously define virtually any scheme.  Well that's the goal anyway, I am sure it needs a lot of work. It also needs some tooling and I am working on that now, as the fires around here have rendered the out-doors unfit for life.

**Comment by jwdonahue** [comment] 2018-10-08 03:45
@mearns, unless you intend to issue a PR or have further comments/questions, please close this thread at your earliest possible convenience. I don't see this idea getting any traction here.  You might want to follow the links I posted in my previous message of @olivier-spinelli.  I am proposing a standard way to define version strings that incorporates more information about regarding the logic used to generate those strings. Working on tooling. Got a long way to go. Input from potential adopters would be useful.

**Comment by chindraba-work** [comment] 2019-03-21 06:08
@mearns As written in SemVer 2.0.0, your use of nightly builds, or any other frequency, are handled perfectly. The only "problem" is that they are not post-release, they are pre-release. 

If you have just released version 2.5.1 (however it was released, and to what ever audience it was released), your next work is not on 2.5.1-dev, but on 2.5.2-dev. Yes, I do know that at the point of issuing the new version number you do not know if it will be a patch-level, minor-level, or major-level change. The SemVer spec, recognized that possibility. 

[Section 9](https://semver.org/#spec-item-9), which covers the pre-release specifically covers the possibility that the changes might be "breaking" 

> A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version.

Since the pre-release version is a series of dot separated identifiers of unbounded length (unbounded in the spec anyway, not necessarily unbounded in-house) the method used can include a timestamp and a developer ID as well, if needed. you could be working on `2.5.2-dev.mearns-20190321T051051` while I am working on `2.5.2-dev.chindraba-20190321T051223`. Your version could even have a breaking change to the public API and mine could have new non-breaking changes to the API. Tomorrow your version `2.5.2-dev.mearns-20190321T211539` could revert those changes and merge mine. At no point in any of the development is the leading version number `2.5.2` being changed, nor does it need to be. As a pre-release it is allowed for the current build to break _anything_ and _everything_ in the API without violating the rules of SymVer. 

When the pre-release version is ready to become a release, then the version number can be set as appropriate: If the API has _any_ breaking change, it becomes 3.0.0. If the API has non-breaking changes, then the new release is 2.6.0. If neither applies, then it is 2.5.2. In any of the three cases, the next development cycle would be numbered as the next patch-level from the just released version (3.0.1-dev, 2.6.1-dev, or 2.5.3-dev).

Now, for the idea that the "release" of your build, nightly or whenever, being the point that it leaves your computer, such as going to the QA team, or the rest of your dev team. What you are working on can be in either of two positions, non-exclusively: top-level element or a dependency. In both cases, if you have induced any API changes, breaking or not, your statement about the QA team is incorrect.

> The QA team can automatically decide which tests to run based on the version because they can tell how it effected the API.

If you make API-level changes, breaking or not, the QA team will have no idea what tests to run because they will not have the new API information available until you provide it to them. If it is a non-breaking new feature, you will have to tell them what that feature is, what it's API spec (interface?) is and what it is supposed to do. If it is a breaking change, you need to tell them what the new version of the API spec is, and how it is different in either the interface or the results. A new minor, or major, version number will not convey that data. The most that they would know from the new version numbers is that there is _some_ change _somewhere_ and they have to find out what that is from you. Outside the QA team the exact same problem occurs: without your input nobody knows what you've done to the API, if anything.

If the project is a top-level element (such as a browser, or command line tool) then, hopefully, it works when you commit it (or do whatever you do to "release" it from your computer), and changes in the API are changes in how it is used or invoked, and those with access to it have been advised that there _might be_ changes by the mere fact that it is a pre-release, nightly build, snapshot, or whatever. Anyone who chooses to use, or rely on, such a release should know that it might be different than it was last time.

If the project is a dependency (which could still be a top-level element as well), then it should _not_ be used outside of a testing environment. The pre-release version tag after the standard version number should prevent it from being automatically updated to, and any developers choosing to use it in the pre-release form has been advised that it is _unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version_ as stated by the SemVer spec.

_Disclaimer_: I'm not, yet, a user of SemVer, let alone a fan, and I have not done Agile, Extreme Programming, or even TDD, as all my development has been done the way I became accustomed to doing it before such things were invented. (Before the Internet was invented as well.)

As I've given at least 2 cents worth, I won't be surprised to be given some change. :)

**Comment by olivier-spinelli** [comment] 2020-06-11 11:19
@alexandrtovmach I don't get the "consensus" idea here. About what?
SemVer handles pre-release. Handling post release is possible as long as you constrain a little bit the possible versions of SemVer. This is what https://csemver.org does:

> CSemVer-CI is an extension that supports CI builds. Its versions follow SemVer 2.0.0, but are not CSemVer compliant. CSemVer-CI defines 2 kind of CI versions:
>
> - ZeroBased
> Versions are based on the 0.0.0 very first version and are smaller than it. Any version of this kind has always a lower precedence than any version of actual releases.
> - LastReleasedBased
> Versions are based on a previous release. They are greater than their base version but always lower than any successor of their base.

**Comment by mentalisttraceur** [comment] 2020-06-11 20:16
@alexandrtovmach I think there is *some* consensus forming towards "if you really need nightly builds to use SemVer, then if there are no actual guarantees about what the public API is, use a `0.0.0` pre-release, otherwise, just use a regular pre-release (but if you don't release your development/nightly builds to the same channel that updates to official finalized releases are regularly installed from, you can just break SemVer, and maybe you should reevaluate if SemVer is actually right for this use case)".

But you will never have overwhelming consensus while SemVer remains dominantly popular, because there are always going to be people who want to shove more features into something, and other people who will assert that those features are unnecessary and symptoms of doing or wanting something else wrongly.

One of the biggest challenges and responsibilities of a maintainer is knowing when to say no to features despite diligently and compassionately considering the desires and reasons for them, and even as users are actively asking for them. Because with a popular project, you'll be getting a lot of people wanting things just because it solves the problem they have *as they have conceptualized it*.

But I do encourage anyone still looking for a solution to SemVer with nightly builds and not satisfied with anything else said here to ask themselves if anything I said in [this comment I just made on another issue](https://github.com/semver/semver/pull/519#issuecomment-642887824) would address that.

**Comment by ygoe** [comment] 2020-06-11 21:02
I also have the impression that "pre-release of the next patch version" seems to be the way that's most suggested and accepted here. I'm using that practice for a while now and so far it looks successful. From [my previous comment](https://github.com/semver/semver/issues/200#issuecomment-347012080), I'd have one suggestion to that to make it less dangerous:

> I'd suggest the following change of mind for this: No pre-release is ever "compatible" with anything but itself. Pre-releases are marked as such for a reason. They may contain any kind of changes at any time. Use them only if you know exactly what you get. So I don't care if 1.0.0 or 1.0.1 are in any way compatible with 1.0.1-something. All I care is that 1.0.0 is compatible with 1.0.1.

As an addition to my earlier statement, I found the metadata to be useful to keep the Git commit hash directly in the version identifier. That makes it easier to find the code that's running if it's not directly tagged as a release. My [versioning tool](https://github.com/ygoe/NetRevisionTask) can add the number of commits since the last version tag, but having the commit hash is easier than counting commits along a branch line.

**Comment by FichteFoll** [comment] 2020-06-14 11:02
Regardless of what is the best currently available workaround, I believe it should be discussed whether this ability should be added to SemVer and if yes, how. I don't think we are at the point in the discussion where we have reached consensus on how to proceed with the proposal. 
For example, If the consensus was "this problem doesn't need solving by SemVer because that only governs outward-facing releases and not internal dev releases", then this would be a reason to close the issue. Extensions of semver to provide the desired feature or the pre-release shenanigan workaround can be used.

However, reality speaks that there are *many* systems out there that provide or utilize automated CI builds and that have no common ground for specifying versions for their artifacts and SemVer *could* step in to fill that void, especially given how popular it is.

I would also like to see a usage study of build metadata for considering whether to allow using that for determining precedence again.

**Comment by steveklabnik** [comment] 2020-06-14 13:25
I personally think this is all handled just fine by the spec as is, and doesn't need to be changed.

**Comment by vcorr** [comment] 2020-09-11 06:05
I'd like to clarify one more thing

@ygoe 
> I also have the impression that "pre-release of the next patch version" seems to be the way that's most suggested and accepted here. I'm using that practice for a while now and so far it looks successful. 

Assume that your latest release is 1.2.0 and it's deployed to production. Then you begin working on 1.2.1-dev or whatever postfix you prefer. You add new features and perhaps even breaking changes. Then a bug is found in production and needs to be patched asap. The sensible version for that bug fix would be 1.2.1. If you deliver that version (obviously from your release branch, including nothing but the bug fix), what happens to your development version number after that?

**Comment by ljharb** [comment] 2020-09-11 06:32
@vcorr the next one would be v1.2.2-dev or whatever postfix you prefer.

**Comment by ygoe** [comment] 2020-09-11 07:48
@vcorr Version numbers are assigned automatically based on previous version tags up the history. The release branch and the main branch are unrelated and will never be merged, so they don't interact with each other regarding their version numbers. It is the task of the maintainer to assign proper version tags. So if I set the 1.2.1 tag on the release/1.2 branch, that doesn't affect the main branch in any way. It will still see 1.2.0 as its latest version tag and continue to generate 1.2.1-dev numbers. But as is the meaning of a pre-release, none of them can be assumed compatible (or ordered across certain boundaries) with any other pre-release. For example, our versions are built like this:

1.2.1-44-feature-name.5+1a2b3c

* 1.2.1 is the next patch version, because we need something that's minimally greater than the latest release 1.2.0.
* - indicates the pre-release
* 44 is the issue number of the work branch
* feature-name is the issue title (44-feature-branch is the full branch name)
* 5 is the number of commits after the latest version tag, 1.2.0. It counts along the path (in Git) so it may become smaller again for new branches.
* 1a2b3c is the commit hash that uniquely identifies the commit we have built. This will be used to find the code for a pre-release version.

Obviously, when you finish work on issue 44 and then continue with issue 38, the version number will appear smaller. But there's no way to change that. This is simply the fate of generated pre-release version numbers in a multi-branch environment. Hence, they must all be assumed incompatible with each other. Only comparisons to release versions or within the same branch are allowed.

**Comment by ljharb** [comment] 2020-09-11 21:34
@ygoe "branches" have nothing to do with semver, nor does your individual repository's workflow. You're making a lot of assumptions about tooling that may not even exist for others, and about what this tooling would do for others. Many workflows don't even have a different "release" and "main" branch - there's just the one main branch, from which all releases are done.

**Comment by ygoe** [comment] 2020-09-11 22:31
@ljharb Then SemVer does not apply to those workflows or leads to undefined behaviour. It's just not specified. So I could only describe my workflow.

**Comment by ljharb** [comment] 2020-09-11 23:21
Totally fine to describe your own workflow! Semver however applies perfectly fine to those workflows, since in many ecosystems, git doesn't contain released artifacts, and an artifact is "published" by pushing to another, separate registry.

**Comment by vcorr** [comment] 2020-09-12 07:34
Since you mentioned release artifacts... Assuming you only have one artifact repository for both prod and dev, how do you deal with the situation, where you have 1.2.0 in production, you are working with 1.2.1-dev towards next release and now you need to make a bug fix to prod with 1.2.1? 

Artefacts repository:
* 1.2.0 (current prod)
* 1.2.1-dev.1 (new features)
* 1.2.1-dev.2 (new features)
* 1.2.1 (bugfix, from release branch etc. , with only the bug fix)
 
1.2.1-dev.3 would be considered earlier than 1.2.1.

For instance Helm charts need to be Semver versioned and if you want to keep your development version open with something like ~1.2.1 it would now pick up the latest of that, 1.2.1 and not 1.2.1-dev.3

**Comment by ljharb** [comment] 2020-09-12 07:42
@vcorr that's why i'd release it as `v1.2.2-dev.0`.

All prereleases are just throwaways. Once v1.2.2 is out, all prereleases for v1.2.2 are obsolete.

In npm, `~` and `^` won't pick up prereleases by default - prereleases are only picked up explicitly.

**Comment by ygoe** [comment] 2020-09-12 09:23
What is an artefact repository? Is that a store for released (binary/compiled) bits? Why should this store contain prereleases? After all, if it's released, it's not a prerelease anymore – it's a release. And that must be assigned a public and comparable version. But if you add a hotfix to 1.2.0 and call it 1.2.1, who says that the main development does contain that fix after all? It could be a fix that's only relevant to the state 1.2.0 was in and may be obsolete by other changes for 1.3.0. So the presence of the fix in the 1.2 branch does not necessarily imply that it's "more" than the current main development. And other prereleases may not even contain that fix because they're built from other unfinished work branches that will never see that fix.

It's complicated and unless you want to assign versions to each commit/prerelease *manually* and *carefully*, you have to use an automatic scheme that cannot consider all parallel developments but only the definitive history of the part to look at. YMMV.

**Comment by ljharb** [comment] 2020-09-13 04:20
For node packages, it’s an npm registry. For ruby gems, it’s rubygems.com or similar. Most languages have some sort of location for published artifacts that’s different from the repository, whether it’s a prerelease or not. Git is for development, not distribution.

**Comment by ygoe** [comment] 2020-09-13 08:01
As I understand it, everything that's published to these locations has a proper assigned version number. This would be tagged as such in Git so that you know what code belongs to that released thing, because somebody external might refer to such a version. Whether it's called 1.0.0 or 1.2.4 or 1.3.6-rc.2. If it contains a dash you must make sure that those versions have a defined order. You probably wouldn't feed daily unreviewed builds automatically into these places, with branch names and commit counts.

**Comment by vcorr** [comment] 2020-09-13 08:29
> You probably wouldn't feed daily unreviewed builds automatically into these places, with branch names and commit counts.

Not to public repositories, no, but depending on your setup it may be required to push them somewhere in order to automate updating development environments. In the production bug fix scenario above, there are two possibilities, either as @ljharb pointed out, bump the patch version in development, or host a completely separate artifact repository for development. I find the first option quite sufficient.

**Comment by jayschwa** [comment] 2020-10-02 05:38
> The next nightly should just be a prerelease. If you don't know what version it'll be, make it a patch prerelease. once you know it's a minor or a major, make it a prerelease of that.

This is worth putting in the FAQ if none of the fancier "ordered, unstable post-release" ideas are likely to be accepted.

**Comment by mentalisttraceur** [comment] 2020-10-02 21:45
@vcorr If you're doing that, the important question is: do you want automatic updates or admins or users to install those nightly builds or not?

Regardless of whether or not you *have* automatic updates, even if you intend to never have them, even if  you teach everyone with download or install permissions to never grab those packages - *if you upload unvetted builds to the same repository as your vetted builds with a higher version number, you are **saying something***.

If you are using a package system which honors SemVer notions of pre-release versions, then that's fine, because in the semantics of that package system, you can say "this is a version you should ignore, because there are no compatibility guarantees" with either pre-release versions or `0.*` versions.

But in package systems that don't do that, you might be saying "this is the newest version, prefer this one unless you know you want an older one".

***If you are using a package system you have to speak its language***.

And that means if you are using it to shove builds into the same update channel as your vetter builds, you have to figure out a way to say "this is not an upgrade" in that package system's language. Otherwise you are lying (in the language of your packaging system). Which might be fine, lying isn't always wrong. You or your team are allowed to decide that a given lie is fine in your case. Just understand it has the same risks and tradeoffs as any other *deliberate miscommunication*.

Drropping the unvetted builds down to `0.*` versions is one way to do that which will say the right thing in many package systems, while saying the right thing in SemVer. (Or if you have official `0.*` releases, you can drop unvetted builds all the way down to `0.0.0-*` as needed.)

But no amount of explicit "nightly" support in SemVer will work around the fact that you'll still have to express "don't update to this!" in the language of your package system, and SemVer can't cover all package systems. For those other package systems, making all your nightlies `0.0.0-*` and putting the other information like git hash or tentative version or last official version after that in the version number is a pretty *universal* fallback.

**Comment by mentalisttraceur** [comment] 2020-10-02 22:09
> > The next nightly should just be a prerelease. If you don't know what version it'll be, make it a patch prerelease. once you know it's a minor or a major, make it a prerelease of that.
>
> This is worth putting in the FAQ if none of the fancier "ordered, unstable post-release" ideas are likely to be accepted.

I think the FAQ should *also* explicitly mention:

1. That maybe your nightlies should not be SemVer'ed at all, even if your official releases are.

2. That maybe package systems which are intended to support nightlies should not force SemVer.

3. The `0.0.0-*` nightly versioning alternative to prerelease versioning, which is the more universal fallback that works in almost all cases.

Because nightly versioning is often a problem of saying the right thing *in the language of your specific package system*, not a problem of saying the right thing in the language of SemVer.

There is some overlap in saying what nightlies want to say in both languages (SemVer pre-releases if the package system knows not to treat them as upgrades) but for the most part they are just separate.

**Comment by alexandrtovmach** [comment] 2021-05-14 18:44
>SemVer spec is something stable and strict, and if you want to change it, please create fork or start another project

closing in favor of https://github.com/semver/semver/issues/703#issuecomment-841420754

**Closed by alexandrtovmach** 2021-05-14 18:44 UTC
Labels: consensus seeking, question
