### ISSUE TITLE
Is An API Needed To Use Semver?

### ISSUE THREAD

**Issue by diligamer** [semver/semver#556] opened 2020-03-31 15:21 UTC
And If So, What Is The Usecase for x.y?

**Comment by jwdonahue** [comment] 2020-04-02 17:07
See #468 and the related links.

Strictly interpreting the spec, yes.  That said, most developer use SemVer to version packages of interfaces and implementations.  It's also used to version some apps.

**Comment by diligamer** [comment] 2020-04-02 19:27
What About Major/Minor In NonAPI Stuff (Apps where you can't use old versions)

**Comment by diligamer** [comment] 2020-04-03 14:36
@jwdonahue

**Comment by jwdonahue** [comment] 2020-04-03 17:21
What about it?  X.Y is not a SemVer string.  The spec covers a specific syntax, semantics and precedence rules.  It is mute on the infinite other possibilities.

Unless you have further questions, please close this thread at your earliest possible convenience.

**Comment by trusktr** [comment] 2020-04-14 21:26
FYI, various tools take `x.y` to mean the equivalent of `^x.y`.

**Comment by trusktr** [comment] 2020-04-14 21:30
@jwdonahue Are things like `~` part of semver? I don't see it listed at https://semver.org

**Comment by jwdonahue** [comment] 2020-04-15 15:43
@trusktr, no they are not.  The spec is mute on range specifications.  Various tools handle them differently.  IMNSHO, modern [set](https://en.wikipedia.org/wiki/Set_theory) and [interval](https://en.wikipedia.org/wiki/Interval_(mathematics)) notation (standard mathematics) is far superior to most of the squiggly, star and other hacks out there.  Any tooling that doesn't use the `[1.0.0, 2.0.0)` form is broken by design.

**Comment by jwdonahue** [comment] 2020-04-15 15:46
@diligamer, unless you require further explanation, please close this thread at your earliest possible convenience.  Thank you.

**Closed** 2020-04-17 10:59 UTC
