### ISSUE TITLE
Handling of text/layout changes/minimal enhancements and public vs private projects

### ISSUE THREAD

**Issue by adamreisnz** [semver/semver#386] opened 2017-08-04 19:39 UTC
Under semver, how does one handle things like:

- Minor text changes
- Minor layout changes
- Updating the readme
- Minimal enhancements

For me they usually fall in a gray area between a patch and minor version, but I was wondering if there's an accepted consensus, or whether it matters that a project is public or private.

For example neither a text change or a layout change "add new functionality to the API" strictly speaking, nor are they really bug fixes. Unless you consider the old text/layout a "bug". So does that mean layout/text changes can be done in patch versions?

The semver specification seems primarily focussed on public packages with publicly consumed API's, but when applied to private projects, it can become harder to differentiate the boundaries between PATCH/MINOR/MAJOR and one might even shift the boundaries altogether, e.g. release patch versions with enhancements, minor versions with larger features including API changes, and major versions only when there are drastic changes to the consumer facing part of the application/complete overhaul.

Curious to hear your thoughts.

**Comment by FichteFoll** [comment] 2017-08-04 20:01
Unless I can see users relying on a certain feature I add, I just default to a patch release. None of the things you list strike me as something a user would rely on, so I'd go with patch for all of them.

**Comment by adamreisnz** [comment] 2017-08-05 00:55
Yes, that's mostly what I do now, for both private and sometimes public projects as well. I guess it just requires a pragmatic approach.

Thanks!

**Comment by raginmari** [comment] 2017-11-12 13:36
Would adding Carthage support (for example) be a patch or minor version increment? It does not add to the public API nor does it alter it, but it is not a bug fix either. It does not affect the code in any way, actually.

Carthage requires a semver tag, so I can't just leave the version number as it is, move the tag and basically update the current version, right?

**Comment by jwdonahue** [comment] 2017-11-28 08:16
This is another instance of "what should get versioned".  If the docs changed, their versions should get bumped appropriately, but some thought has to go into the impact at the distribution package version level. If the docs were woefully incomplete say when 1.0.0 of the package was released, and you put a lot of effort into them, you have every right to brag about major new features, even if they are pure document changes, but you might not have to; if the new docs don't expressly prohibit some known usage patterns that have caused problems for product support staff. If they do, then you have probably owe your customers a major version bump on the package.

**Comment by jwdonahue** [comment] 2018-07-12 21:07
@adamreisnz, any further question on this matter?  If there are no outstanding actionable asks here and your questions have been answered, please close this issue at your earliest possible convenience. Thank you.

**Closed** 2018-07-13 01:07 UTC
