### ISSUE TITLE
The semver.org rendering of semver.md mangles important consecutive dashes

### ISSUE THREAD

**Issue by abrudz** [semver/semver#659] opened 2021-02-11 16:02 UTC
> 9. (…) Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. (…) 1.0.0-x-y-z.–.

Note the En-dash after `x-y-z.` The source has two dashes: `--`

>10. (…) Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. (…), 1.0.0+21AF26D3—-117B344092BD.

Note the Em-dash before `-117`. The source has four dashes: `----`

**Comment by Nixinova** [comment] 2021-02-13 05:24
Dupe of #616 & https://github.com/semver/semver.org/issues/291

**Comment by alexandrtovmach** [comment] 2021-06-14 04:19
Thanks for report, but it's duplicate. Closed in favor of #616 & semver/semver.org#291

**Closed by alexandrtovmach** 2021-06-14 04:19 UTC
