### ISSUE TITLE
One of the examples renders incorrectly

### ISSUE THREAD

**Issue by masaers** [semver/semver#822] opened 2022-04-12 01:00 UTC
The last example under point 9 of the Semantic Versioning Specification contains an identifier constituting two dashes. This renders as an n-dash when converted to HTML, which is not a correct identifier.

**Comment by JohnTitor** [comment] 2022-08-13 14:36
Duplicate of https://github.com/semver/semver.org/issues/320

**Closed by JohnTitor** 2022-08-13 14:36 UTC
