### ISSUE TITLE
clarification on "API" meaning in case of executables versioning

### ISSUE THREAD

**Issue by mastupristi** [semver/semver#555] opened 2020-03-28 18:01 UTC
Throughout the text you refer to the term **API** (Application programming interface):

> For this system to work, you first need to declare a **public API**. This may consist of documentation or be enforced by the code itself. Regardless, it is important that this **API** be clear and precise. Once you identify your **public API**, you communicate changes to it with specific increments to your version number. Consider a version format of X.Y.Z (Major.Minor.Patch). Bug fixes not affecting the **API** increment the patch version, backwards compatible **API** additions/changes increment the minor version, and backwards incompatible **API** changes increment the major version.

The term "public APIs" makes me think of a library that should provide functionality and for this reason it is necessary to define public APIs to which the concepts of compatibility/incompatibility that drive the version change apply. Isn't that right?

But I write bare-metal executables for embedded devices. They do not expose any API. How should I implement the change of MAJOR, MINOR and PATCH?

best regards
Max

**Comment by ljharb** [comment] 2020-03-28 18:34
Duplicate of #554.

**Closed** 2020-03-28 20:13 UTC
