### ISSUE TITLE
What if only change is requiring higher version of Java

### ISSUE THREAD

**Issue by JMarkMurphy** [semver/semver#534] opened 2019-09-17 18:48 UTC
If the public interface does not change, but only dropping support for older unsupported versions of Java, does that constitute a breaking change?

**Comment by wizzwizz4** [comment] 2019-09-17 18:51
Does anybody still _use_ those Java versions?

**Comment by ljharb** [comment] 2019-09-17 19:12
Yes, because a user on that version would be broken.

**Comment by JMarkMurphy** [comment] 2019-09-17 19:39
Maybe, dropping support for Java 6 and 7.

**Comment by ljharb** [comment] 2019-09-18 02:32
semver is more about theoretical breakage than actual breakage - someone somewhere might be using those versions, thus dropping them is semver-major.

**Comment by klehelley** [comment] 2019-09-18 08:08
What do you mean by "dropping support"? Is it "if you find an issue with new versions of the software, and you use an old Java version, we won't help you", or "new versions are compiled with Java 7 and thus people still using Java 6 will NOT be able to use it as the JVM will complain and stop if they try to"?

In the former case this is a non-technical decision, and it is up to you if you want to increase the MAJOR version (SemVer does not forbid it and it will likely make things clearer to your users) or not. In the latter case it is definitely a breaking change.

**Comment by ljharb** [comment] 2019-09-18 17:39
(Personally I consider both semver-major, but I do agree that the latter case is objective and the former subjective)

**Comment by jwdonahue** [comment] 2019-09-23 00:26
@JMarkMurphy, was your API modified to use new language support?  Or is this a binary level breaking change?  What packaging tool(s) are you using?

I am not a Java coder, but I think from earlier discussions, that I gather that in the Java community, if you force your customers to upgrade their environment to run your code, they expect you to bump the major version.  Unless your tool-chain supports side-by-side execution of different versions of Java, you should bump the major version or expect to face the wrath of your customers.  It's a judgement call, whether that wrath is worthy of avoidance.

This a among the most common questions we get here.  Try searching for "transient", "dependency", "dependencies" and "environment".  The root of the problem is, _are you actually applying the version string to an API, implementation or package of API/implementation_?  The spec offers the best clarity on versioning API's, but most of us are actually adapting SemVer to collections of stuff (aka; packages).

**Comment by jwdonahue** [comment] 2019-10-03 07:46
@JMarkMurphy, unless you have follow-up information/questions, please close this thread at your earliest possible convenience.

**Comment by jwdonahue** [comment] 2020-01-07 18:05
@JMarkMurphy, unless you have further questions, this thread should be closed.

**Comment by filips123** [comment] 2020-04-29 22:40
I have a similar question, except not for removing support for old Java versions, but generally removing support for old language versions.

Most package managers detect if the current language version if unsupported by library/project and prevent updating to it. Because of that, it doesn't matter which type of release are you going to make, because the package manager will prevent users from updating to it and breaking stuff.

However, how does SemVer consider this?

**Comment by ljharb** [comment] 2020-04-29 23:09
That the package manager can also determine that for you seems independent of the version number imo; if it's breaking if it *were* installed, it's breaking.

**Closed** 2020-08-12 15:10 UTC
Labels: question
