### ISSUE TITLE
Problems with the Magic Zero

### ISSUE THREAD

**Issue by isaacs** [semver/semver#221] opened 2014-09-04 22:16 UTC
The "anything may change at any time" nature of a leading zero major version is somewhat disruptive for authors who may feel intimidated at the perceived commitment involved in a `1.0.0` release.

We may all have see The Light, and realized that the number `1` is in fact a perfectly fine place to start counting our releases, and casually increment the major version with every breaking change if that change provides some value.  But many are timid, and talking them out of their timidity is very difficult.

Yet, the language in section 4 makes it very difficult to rely on pre-1.0 code.  I believe that this _increases_, rather than decreases, the trepidation at marking something 1.0.  It would be better with a slight increase in commitment; a stepping stone from the wild world of `0.0.4` up to the public scrutiny of `1.2.3`.

This would also allow project authors to communicate non-breaking additive changes in the `0.x.y` version families.  In practice, many seem to treat the transition from `0.9.2` to `0.9.3` as a non-breaking change, whereas they'd treat `0.9.2` to `0.10.0` as potentially introducing breaking changes.  (Node, for example, operates this way, though that is a pretty egregious example of [Sentimental Versioning](http://sentimentalversioning.org/).)

In effect, the left-most non-zero version number is the "effective major version", and incrementing it indicates a breaking change.  The next place is the "effective minor version", and the third is the "effective patch version".  This allows authors to more gradually shift from "anything goes" to "grownup".

The `^` operator in https://github.com/isaacs/node-semver used to operate this way, until some users requested that it instead follow the SemVer specification.  However, shifting to `^0.x.y` meaning "exactly equal to 0.x.y" has proven very problematic in practice.

I haven't wordsmithed this very much, but this is a first-pass at some language we could use to express this.  If others on this repo feel it's worthwhile, I'd be happy to send a proper pull request.

``` patch
diff --git a/semver.md b/semver.md
index 0c060db..8dfdc06 100644
--- a/semver.md
+++ b/semver.md
@@ -68,8 +68,14 @@ Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.
 1. Once a versioned package has been released, the contents of that version
 MUST NOT be modified. Any modifications MUST be released as a new version.

-1. Major version zero (0.y.z) is for initial development. Anything may change
-at any time. The public API should not be considered stable.
+1. Major version zero and minor version zero (0.0.z) is for initial
+development. Anything may change at any time. The public API should
+not be considered stable.
+
+1. Major version zero and minor version greater than zero (0.y.z) is
+for beta development. Additive changes may be introduced by
+incrementing the patch version. Breaking changes may be introduced by
+incrementing the minor version.

 1. Version 1.0.0 defines the public API. The way in which the version number
 is incremented after this release is dependent on this public API and how it

```

cc @Haacked @mojombo @othiym23 @domenic @ceejbot

**Comment by jwdonahue** [comment] 2017-12-07 23:58
IMO, 0.x.y or 0.0.y should both be banned from the SemVer spec in version 3.0.0. The -prerelease tag effectively has the same default semantics. Virtually all packaging schemes seem to cover the prerelease tag semantics quite well. Dropping the 0.x.y loop-hole would simplify the world and add the ability for developers to tell their customers, _here's what I think is just a new non-breaking feature, but I know this technology is immature and we're still receiving surprising feed-back from our customers so I have this prerelease tag on it because I am uncertain that I won't break a significant number of my customers_.

Forcing all prerelease versions to have a prerelease tag on them, frees up the entire SemVer triplet for the package producers to advertise their full intent while simultaneously tagging the release as risky.

**Comment by jwdonahue** [comment] 2017-12-07 23:59
@isaacs, unless you intend to pursue this issue further, please close this issue at your earliest possible convenience.

**Closed** 2017-12-08 01:14 UTC

**Comment by elypter** [comment] 2018-02-07 17:35
couldn't this all be solved if you add the exception that you can bump from 0.x.y to 1.0.0 without needing a breaking change? just allow people to bump when they feel the project is ready but the interface wont change anytime soon. if this is part of the standard then applications will simply ignore the pseudo major bump. the only downside is that you cannot do a major change while jumping to 1.0.0 but then you can still just do it right before.

**Comment by jwdonahue** [comment] 2018-02-07 22:15
The standard already specifies that 1.0.0 is the first stable version.  Literally every change up to and including the 1.0.0 release is potentially, but not required to be, a breaking change.  In other words, risk averse consumers wait for 1.0.0.  From that point forward, you should not bump the major version unless you have actually introduced breaking changes.

**Comment by elypter** [comment] 2018-02-08 03:24
couldn't this all be solved if you add the exception that you can bump from 0.x.y to 1.0.0 without needing a breaking change? just allow people to bump when they feel the project is ready but the interface wont change anytime soon. if this is part of the standard then applications will simply ignore the pseudo major bump. the only downside is that you cannot do a major change while jumping to 1.0.0 but then you can still just do it right before.

**Comment by elypter** [comment] 2018-02-08 03:26
maybe make this more clear in the manifest so nobody gets the idea that you cannot just bump to 1.0.0 if you think the time is right.

**Comment by jwdonahue** [comment] 2018-02-09 22:28
@elypter,

People get all kinds of ideas in their heads.  The spec can't possibly account for every irrational idea that might come into every developer's head.  That said, I would personally prefer to see the 0.x.y release mode removed from the spec in vesion 3.x.x.  The prerelease tag can be used effectively to cover all prerelease contingencies.  The current spec essentially requires that all 0.x.y versions must be treated as prerelease anyway, so why have two forms?  Well, it's probably historical, so it was captured in early versions of the spec, but we don't have to continue to perpetuate it.

Related: #287, #333, #238.

**Comment by grv87** [comment] 2018-04-29 10:11
@jwdonahue, could you clarify your opinion? Does I make these right?

1. If my library's version is `0.25.47`, it becomes not complaint to the standard. I should release `0.25.48-prerelease` instead.
2. I can't increment major version if I don't have breaking changes.
3. Starting new library I must use `1.0.0-prerelease` version.

If these are correct, then it looks OK for new libraries but not for existing. How, having `0.25.48-prerelease`, I could make a release not making breaking changes?
Or commit with incremented major version is considered as a breaking change itself?

**Comment by jwdonahue** [comment] 2018-04-30 21:29
@grv87 ,

The spec _explicitly_ spells out what you must and should do as a publisher, when you make certain kinds of changes, depending on whether they break back-compat (major bump), add back-compat (minor bump) features or just publish changes with no new features (patch). It does not prohibit version changes in the absence of underlying product changes. In fact, the only way to recover from publishing errors is to remove the erroneously versioned package from public feeds and issue a new package with a correct version number based on the rules (ie, two packages in the world with identical content and two different version numbers is okay, but probably SHOULD be avoided). 

The spec also _implicitly_ defines expected risk levels to consumers of your published packages and therefore also guides their policy choices in automatically accepting updates.  If you have been publishing a series of 0.y.z releases, your consumers are already treating them as though each release is very risky and also might be valuable to them. They are in a co-development phase with you and are eagerly awaiting completion of a relatively bug free and stable product. They may be taking every update from you, testing it and then deciding whether to publish their own bits that include your updates, or they may be stuck on a more-or-less useful version for their own purposes and waiting for you to complete the project before they devote much more effort into taking a new update. It's actually a continuum between those extremes for most of your consumers.

An arbitrary change on your part from 0.y.z to 1.y.z-prerelease might trigger some of your customers to take a closer look at your new release, and that will likely consume some of their resources. In the absence of guidance from you, they might assume that you are entering a more stable phase than in the past. Most of their tooling however, should distinguish both 0.25.48 and 1.0.0-tag as being of the prerelease risk class, but I don't know that there aren't some tools out there, that break the prerelease category down to higher and lower prerelease subcategories. 

No-one has labeled my earlier suggestion as barking mad, yet, so I take that as a good sign, but you have to consider what _you_ know about _your_ customers and make the correct choices for you and them, to the best of your abilities.  I can only make some general recommendations how you might convert to the prerelease tag form from the development form. First, taking your example above, your next release would be 0.26.0, whether or not you added new features or breaking changes, because you're about to make a big change in your versioning semantics. You include in the your release notes, a prominent notice of the intended change in versioning and the next package version number, which will be 1.0.0-a.dev (or whatever tag is appropriate for you) and except for a change in the release notes, that package contains the same bits as 0.26.0.  Your customers can then fix any knock-on bugs in their own products caused by integrating 0.26.0, review and adjust their intake policies and then verify that the entire publish/consume chain of events works correctly, without having to worry about changes in your code.

Personally, I would only go to all that trouble, if I was going to produce new products. In that case, I wouldn't want to be supporting different workflows for different products. If I had been using the 0.y.z scheme on an earlier product line, I would convert.  After working with semantic versioning for several years and having developed tooling around it, I see an advantage to the 1.0.0-X.Y.Z.Tag form of prerelease series, where the X.Y.Z are given full SemVer semantics and it is obvious to everyone that the target release is 1.0.0. It conveys a richer set of information to my consumers and it allows me to more easily support overlapping version 1 and version 2 projects (ie, development on N and maintenance on N-1).  I tend to fix bugs first, then do features, so my typical version history might look something like:

1.0.0-0.1.0.dev  // Made available to QA and very early adopters (VEA's).
1.0.0-1.0.0.dev // Just broke the world.
1.0.0-1.0.1.dev // Bug fixes.
1.0.0-1.1.0.dev // Making progress on the feature set.
1.0.0-1.1.1.dev // More bug fixes.
1.0.0-1.1.2.flight0 // Dogfood release.
1.0.0-1.1.2.flight1 // Wow, good at this, let some outside early adopters have a look.
1.0.0-1.1.3.flight2 // Fixed bugs, widen audience.
...
1.0.0-Alpha.1 // Earliest generally available release.
1.0.0-1.1.4.dev // Bug fixes for QA and VEA's.
1.0.0-Beta.1  // Getting closer. This is 1.0.0-1.1.4.dev with a new label on it.
1.0.0-RC.1  // Locked down, only bug fixes from here on out.
2.0.0-0.1.0.dev // Moved resources to next generation.
1.0.0-1.1.4.dev // QA & VEA's
1.0.0-RC.2 // Decided to 1.0.0-1.1.4.dev is RC quality, publish it.
... A bunch of version 2 series releases ...
1.0.0 // New cars start showing up in the parking lot :)
2.0.0-1.0.0.dev // Lots of next gen work going on.
1.0.1-1.1.3.dev // Bug fixes in the works for v1.
etc...

The above version history is a plausible SemVer compliant sequence. Some CI tooling already supports it, some don't, in fact, some get in the way of implementing it like that.  Obviously, not all of those versions are available to everyone.

Unfortunately, SemVer does not provide the means for defining the semantics for the prerelease tag identifiers (fields), beyond their sort order. Pure numeric prerelease identifiers sort lower than alpha-numeric identifiers. I have been working on and off, over the past few months, on a scheme to provide the means for developers to publish the full semantics of every field in their version scheme. A human and machine readable VersionSchema is required to bring more order to semantic versioning.

See [https://VersionMeta.org/](https://VersionMeta.org/) and stay tuned.

**Comment by grv87** [comment] 2018-05-04 10:18
IMO, @ronen suggestion to just drop rules 4 and 5 is simpler.
But I can't see any practical difference, turns out it's just personal preference to start major versions from 0 or from 1. When I use semantic release tool it starts versions from 1.0.0 anyway.

When we could expect semver 3.0.0 prerelease with changed magic zero rule?
